DROP TABLE users IF EXISTS;
DROP TABLE property_type IF EXISTS;
DROP TABLE property_type IF EXISTS;
DROP TABLE properties IF EXISTS;


CREATE TABLE users (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  password  VARCHAR(255)
);
CREATE INDEX users_name  ON users (name);
CREATE INDEX users_email  ON users (email);

CREATE TABLE property_type (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX property_type_name ON property_type (name);

CREATE TABLE properties (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_type_id     INTEGER,
  price  DOUBLE,
  title VARCHAR(255),
  address VARCHAR(255),
  image VARCHAR(255)
);
ALTER TABLE properties ADD CONSTRAINT fk_properties_property_type FOREIGN KEY (property_type_id) REFERENCES property_type (id);